name: image-insights

on:
  # The schedule will trigger in the UTC timezone
  #schedule:
  #- cron: "0 19 * * *"
  push:
    branches:
      - main

jobs:
  publish-insights:
    env:
      REGISTRY: ghcr.io
      ORG: santoshkal
    runs-on: ubuntu-latest
    permissions:
      content: write
      id-token: write
      actions: read

      steps:
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Set up Docker Buildx caching (optional)
          uses: docker/cache-action@v2
          with:
            path: /tmp/.buildx-cache

        - name: Run Docker Buildx imagetools inspect
          run: |
            docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.ORG }}/ansible:v1.0.0 \
              --format '{{ json .Provenance.SLSA }}' > ./ansible-provenance.json
          # - name: Publish SBOM report
          #
          # - name: Publish SLSA provenance report
          #
          # - name: Publish CVE and recomendations
