name: image-insights

on:
  # The schedule will trigger in the UTC timezone
  #schedule:
  #- cron: "0 19 * * *"
  push:
    branches:
      - main

jobs:
  publish-insights:
    env:
      REGISTRY: ghcr.io
      ORG: santoshkal
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - name: ansible
    permissions:
      contents: write
      id-token: write
      actions: read
      pull-requests: write

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: "0"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3

      - name: Cache Docker layers
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Collect Provenance
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.ORG }}/${{ matrix.image.name }}:v1.0.0 \
            --format '{{ json .Provenance.SLSA }}' > ./${{ matrix.image.name }}-attestations/${{ matrix.image.name }}-provenance.json

      - name: Collect SBOM
        run: |
          docker buildx imagetools inspect ${{env.REGISTRY}}/${{ env.ORG }}/${{ matrix.image.name }}:v1.0.0 \
            --format '{{ json .SBOM.SPDX }}' > ./${{ matrix.image.name }}-attestations/${{ matrix.image.name }}-sbom.jaon

      - name: Docker Scout
        id: scout
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{env.REGISTRY}}/${{ env.ORG }}/${{ matrix.image.name }}:v1.0.0
          to: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.COMPARE_TAG }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Collect CVES
        run: |
          echo "${{ steps.scout.outputs.cves }} > ./${{ matrix.image.name }}-attestations/${{ matrix.image.name }}-CVES.md "

      - name: Commit Provenance File to Repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./${{ matrix.image.name }}
          git commit -m "Add ansible attestation files"
          git push origin main
