name: image-insights

on:
  # The schedule will trigger in the UTC timezone
  #schedule:
  #- cron: "0 19 * * *"
  push:
    branches:
      - main

jobs:
  publish-insights:
    env:
      REGISTRY: ghcr.io
      ORG: santoshkal
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      actions: read

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Run Docker Buildx imagetools inspect
        id: inspect
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.ORG }}/ansible:v1.0.0 \
            --format '{{ json .Provenance.SLSA }}'

      - name: Check Provenance content
        run: "echo ${{ steps.inspect.outputs }}"

      # - name: Write Provenance File to Repository
      #   uses: DamianReeves/write-file-action@6929a9a6d1807689191dcc8bbe62b54d70a32b42 # v1.3
      #   with:
      #     path: "./ansible-provenance.json"
      #     contents: |
      #       ```
      #       ./ansible-provenance.json
      #       ```
      #     message: "Add ansible provenance file"
      #     overwrite: true
      # - name: Commit & Push
      #   uses: Andro999b/push@c77535fe7a94645f7ceca83e48e6cc977620710e # v1.3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.run_number }}"
      #     force: true
      #     message: "Overwritten by GitHub Actions - ${{ github.run_number }}"
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.run_number }}"
      #     title: "Ansible provenance from ${{github.run_number}}"
      #     body: "This pull request updates the ansible-provenance"
      #     base: main
