name: image-insights

on:
  # The schedule will trigger in the UTC timezone
  #schedule:
  #- cron: "0 19 * * *"
  push:
    branches:
      - main

jobs:
  publish-insights:
    env:
      REGISTRY: ghcr.io
      ORG: santoshkal
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      actions: read
      pull-requests: write

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: "0"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Run Docker Buildx imagetools inspect
        id: inspect
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.ORG }}/ansible:v1.0.0 \
            --format '{{ json .Provenance.SLSA }}' > ./ansible-provenance.json
