name: build-push-ansible

on:
  schedule:
    - cron: "35 18 * * *"

jobs:
  build-push-ansible:
    env:
      REGISTRY: ghcr.io
      IMAGE: santoshkal/ansible
      TAG: "v1.0.0"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      #Checks out in to the repo we are working on
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up cosign
        uses: sigstore/cosign-installer@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Login to Github Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}

      - name: sign container image
        run: |
          cosign sign  ${{ env.REGISTRY }}/${{ env.IMAGE }}@${{ steps.docker_build.outputs.digest}} --yes
