name: build-push-ansible

on:
  # The schedule will trigger in the UTC timezone
  #schedule:
    #- cron: "0 19 * * *"
   push:
     branches:
       - main

jobs:
  build-push-ansible:
    env:
      REGISTRY: ghcr.io
      IMAGE: santoshkal/ansible
      TAG: "v1.0.0"
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      packages: write
      id-token: write
    steps:
      #Checks out in to the repo we are working on
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up cosign
        uses: sigstore/cosign-installer@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Login to Github Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}

      - name: Generate SBOM
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b $HOME/.local/bin
          $HOME/.local/bin/syft ${{ secrets.DOCKER_USERNAME }}/my-image:latest -o cyclonedx-json > sbom.json

      - name: Push SBOM to Registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          cat sbom.json | docker exec -i $(docker run -d --rm --entrypoint sh dockerhub/pushsbom) tee /tmp/sbom.json
          docker cp /tmp/sbom.json $(docker ps -lq):/sbom.json
          docker commit $(docker ps -lq) ${{ secrets.DOCKER_USERNAME }}/my-image:sbom-latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-image:sbom-latest
  
      - name: sign container image
        run: |
          cosign sign  ${{ env.REGISTRY }}/${{ env.IMAGE }}@${{ steps.docker_build.outputs.digest}} --yes
