name: build-push-ansible

on:
  # The schedule will trigger in the UTC timezone
  #schedule:
  #- cron: "0 19 * * *"
  push:
    branches:
      - main

jobs:
  build-push-ansible:
    env:
      REGISTRY: ghcr.io
      IMAGE: santoshkal/ansible
      TAG: "v1.0.0"
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      packages: write
      id-token: write
    steps:
      #Checks out in to the repo we are working on
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
        with:
          go-version: "1.22"

      - name: Install Genval
        run: go install github.com/intelops/genval@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up cosign
        uses: sigstore/cosign-installer@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Login to Github Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}

      - name: generate SBOM for the image
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}
          artifact-name: ansible-sbom.spdx.json

      - name: Move SBOM to tmp
        run: |
          SBOM_DIR=/tmp/sbom
          mkdir -p $SBOM_DIR
          mv /tmp/sbom-action-*/ansible-sbom.spdx.json $SBOM_DIR/
          echo "SBOM_DIR=$SBOM_DIR" >> $GITHUB_ENV

      - name: Push SBOM as OCI artifact to GHCR
        run: |
          genval artifact push --reqinput ${{ env.SBOM_DIR }} \
          --dest oci://${{ env.REGISTRY }}/${{ env.IMAGE }}-${{ env.TAG }}.sbom \
          --annotations="authors=intelops inc."

      - name: sign container image
        run: |
          cosign sign  ${{ env.REGISTRY }}/${{ env.IMAGE }}@${{ steps.docker_build.outputs.digest}} --yes
